export const VINTANA_SIGNS = [
  {
    id: 'alahamady',
    name: 'Alahamady',
    nameFr: 'Alahamady (Le Guide Royal)',
    westernZodiac: 'Bélier',
    symbol: 'Mpanjaka sy Fanilo',
    element: 'afo',
    elementLabelMg: 'Afo (Feu)',
    elementLabelFr: 'Feu sacré',
    cardinalZoro: 'Zoro Alahamady (Avaratra-Atsinanana)',
    cardinalFr: 'Nord-Est (Coin sacré de la royauté)',
    solarPeriodFr: '21 Mars – 19 Avril',
    personalityMg:
      'Olona mpitarika, manan-kaja, be herim-po ary mahay mandray andraikitra. Ny fanahiny dia toy ny afo miredareda manazava ny manodidina.',
    personalityFr:
      "Leader né, porteur de dignité, de courage et d'autorité bienveillante. Son esprit éclaire son entourage telle une flamme noble.",
    strengthsMg: [
      'Fahasahiana',
      'Fahitsiana',
      'Fahaiza-mitarika',
      'Fikirizana',
    ],
    strengthsFr: ['Courage', 'Loyauté', 'Leadership naturel', 'Persévérance'],
    adviceMg:
      "Tandremo ny rehaka sy ny firehetana tampoka ; ampiasao amin'ny fanasoavana ny herinao.",
    adviceFr:
      'Canalisez votre fougue et cultivez la patience pour guider sans imposer.',
    luckyDayMg: 'Alakamisy',
    luckyDayFr: 'Jeudi',
    proverbMg: 'Izay mahay mandefitra no lava andro iainana.',
    proverbFr: "Celui qui sait temporiser s'assure une longue vie féconde.",
    startMonth: 3,
    startDay: 21,
    endMonth: 4,
    endDay: 19,
  },
  {
    id: 'adaoro',
    name: 'Adaoro',
    nameFr: 'Adaoro (La Force Calme)',
    westernZodiac: 'Taureau',
    symbol: 'Omby sy Tany Mahavokatra',
    element: 'tany',
    elementLabelMg: 'Tany (Terre)',
    elementLabelFr: 'Terre fertile',
    cardinalZoro: 'Atsinanana (Est)',
    cardinalFr: 'Est (Le Levant)',
    solarPeriodFr: '20 Avril – 20 Mai',
    personalityMg:
      'Matotra, mahatoky ary tia filaminana. Mpikarakara mahay mamelona sy miaro ny ankohonana sy ny harena.',
    personalityFr:
      'Posé, fidèle et bâtisseur. Il cultive la stabilité matérielle et humaine, protégeant avec ténacité ce qui lui est cher.',
    strengthsMg: ['Faharetana', 'Fahatokisana', 'Fahazotoana', 'Fahendrena'],
    strengthsFr: ['Patience', 'Fiabilité', "Sens de l'effort", 'Stabilité'],
    adviceMg:
      'Aza matahotra ny fiovana ; ny rivotra vaovao dia mitondra oram-pahasoavana.',
    adviceFr:
      "N'ayez pas peur de l'inattendu ; la nouveauté apporte aussi la prospérité.",
    luckyDayMg: 'Zoma',
    luckyDayFr: 'Vendredi',
    proverbMg:
      'Ny omby mahia tsy mba namana, fa ny tany mahavokatra no itokiana.',
    proverbFr:
      'La constance et le travail fécond surpassent toujours les promesses éphémères.',
    startMonth: 4,
    startDay: 20,
    endMonth: 5,
    endDay: 20,
  },
  {
    id: 'adizaoza',
    name: 'Adizaoza',
    nameFr: "Adizaoza (L'Éloquent & Curieux)",
    westernZodiac: 'Gémeaux',
    symbol: 'Rivotra sy Teny Mamy',
    element: 'rivotra',
    elementLabelMg: 'Rivotra (Air)',
    elementLabelFr: 'Air vivifiant',
    cardinalZoro: 'Atsinanana-Atsimo-Atsinanana',
    cardinalFr: 'Est-Sud-Est',
    solarPeriodFr: '21 Mai – 20 Juin',
    personalityMg:
      "Tia karokaroka, malaky saina, mahay kabary ary mora mahazo namana. Mahita vahaolana hatrany amin'ny sarotra.",
    personalityFr:
      "Vif d'esprit, communicatif et sociable. Il a l'art de la parole, de la diplomatie et sait créer des passerelles entre les êtres.",
    strengthsMg: [
      'Fahaiza-miteny',
      'Fahamailoana',
      'Fihavanana',
      'Fahakingana',
    ],
    strengthsFr: [
      'Éloquence',
      'Adaptabilité',
      'Facilité relationnelle',
      'Esprit vif',
    ],
    adviceMg:
      "Aza avela hiparitaka loatra ny eritreritrao ; mifantoha amin'ny zava-dehibe.",
    adviceFr:
      'Évitez la dispersion mentale ; concentrez votre énergie sur vos projets prioritaires.',
    luckyDayMg: 'Alarobia',
    luckyDayFr: 'Mercredi',
    proverbMg: 'Ny teny toy ny atody, ka raha vaky tsy azo atambatra.',
    proverbFr:
      'La parole est un joyau précieux ; mesurez son poids avant de la libérer.',
    startMonth: 5,
    startDay: 21,
    endMonth: 6,
    endDay: 20,
  },
  {
    id: 'asorotany',
    name: 'Asorotany',
    nameFr: 'Asorotany (Le Protecteur du Foyer)',
    westernZodiac: 'Cancer',
    symbol: 'Akany sy Rano Madio',
    element: 'rano',
    elementLabelMg: 'Rano (Eau)',
    elementLabelFr: 'Eau protectrice',
    cardinalZoro: 'Zoro Asorotany (Atsimo-Atsinanana)',
    cardinalFr: 'Sud-Est (Angle de la famille)',
    solarPeriodFr: '21 Juin – 22 Juillet',
    personalityMg:
      'Be fitiavana, saro-pady, manome lanja lehibe ny havana sy ny fomban-drazana. Manana fahatsapana anaty lalina.',
    personalityFr:
      "Dévoué, sensible et profondément attaché aux siens. Doté d'une forte intuition, il veille sur l'harmonie du foyer.",
    strengthsMg: [
      'Fandavan-tena',
      'Fahatsapan-tena',
      'Fitiavana',
      'Fahatsiarovana',
    ],
    strengthsFr: [
      'Bienveillance',
      'Intuition',
      'Attachement familial',
      'Générosité',
    ],
    adviceMg: 'Mianara mamela heloka ary aza mitahiry alahelo ela ao am-po.',
    adviceFr:
      'Laissez couler les rancœurs passées pour préserver votre paix intérieure.',
    luckyDayMg: 'Alatsinainy',
    luckyDayFr: 'Lundi',
    proverbMg:
      'Ny fihavanana toy ny volo-katsaka, ka sady mamelona no manarona.',
    proverbFr:
      'La fraternité est comme la robe du maïs : elle nourrit et réchauffe à la fois.',
    startMonth: 6,
    startDay: 21,
    endMonth: 7,
    endDay: 22,
  },
  {
    id: 'alahasaty',
    name: 'Alahasaty',
    nameFr: 'Alahasaty (Le Rayonnant)',
    westernZodiac: 'Lion',
    symbol: 'Masoandro sy Herim-po',
    element: 'afo',
    elementLabelMg: 'Afo (Feu)',
    elementLabelFr: 'Feu solaire',
    cardinalZoro: 'Atsimo (Sud)',
    cardinalFr: 'Sud (Zénith éclatant)',
    solarPeriodFr: '23 Juillet – 22 Août',
    personalityMg:
      "Tia mitsiky, be fahalalahan-tanana, sahy mijoro ho an'ny rariny ary manana herin-tsaina manintona.",
    personalityFr:
      "Chaleureux, généreux et intègre. Sa présence inspire confiance et son magnétisme naturel rassemble ceux qui l'entourent.",
    strengthsMg: [
      'Fahalalahan-tanana',
      'Faherezana',
      'Fahamarinana',
      'Hatsaram-panahy',
    ],
    strengthsFr: [
      "Grandeur d'âme",
      'Courage',
      'Magnétisme',
      'Sens de la justice',
    ],
    adviceMg:
      "Mihainoa ny hafa alohan'ny hanapa-kevitra ; ny hevitry ny maro no mahasoa.",
    adviceFr:
      "Sachez écouter les avis discrets ; la véritable force réside dans l'humilité.",
    luckyDayMg: 'Alahady',
    luckyDayFr: 'Dimanche',
    proverbMg:
      "Ny hazo tokana tsy mba ala, ary ny herin'ny maro maharesy ny sarotra.",
    proverbFr:
      'Un arbre seul ne fait pas la forêt : le partage démultiplie la lumière.',
    startMonth: 7,
    startDay: 23,
    endMonth: 8,
    endDay: 22,
  },
  {
    id: 'asombola',
    name: 'Asombola',
    nameFr: "Asombola (L'Artisan de l'Abondance)",
    westernZodiac: 'Vierge',
    symbol: 'Vary sy Haron-karena',
    element: 'tany',
    elementLabelMg: 'Tany (Terre)',
    elementLabelFr: "Terre d'abondance",
    cardinalZoro: 'Atsimo-Andrefana',
    cardinalFr: 'Sud-Ouest',
    solarPeriodFr: '23 Août – 22 Septembre',
    personalityMg:
      'Mahay mikaly, mandinika tsara ny antsipiriany, tia fahadiovana sy filaminana. Mpitahiry ny vokatry ny asa.',
    personalityFr:
      'Pragmatique, méticuleux et observateur. Il sait transformer chaque graine en récolte abondante grâce à son sens du détail.',
    strengthsMg: ['Fandaminana', 'Fahamalinana', 'Fahaiza-manao', 'Fahitsiana'],
    strengthsFr: ["Sens de l'organisation", 'Précision', 'Modestie', 'Rigueur'],
    adviceMg:
      "Aza manahy be loatra ny amin'ny ampitso ; ankafizo ny voa efa voatahiry.",
    adviceFr:
      'Ne laissez pas le perfectionnisme étouffer la joie du moment présent.',
    luckyDayMg: 'Alarobia',
    luckyDayFr: 'Mercredi',
    proverbMg: 'Izay mamafy am-paharitana no mijinja am-pifaliana.',
    proverbFr: 'Celui qui sème avec rigueur récolte dans la sérénité.',
    startMonth: 8,
    startDay: 23,
    endMonth: 9,
    endDay: 22,
  },
  {
    id: 'adimizana',
    name: 'Adimizana',
    nameFr: "Adimizana (L'Arbitre du Fihavanana)",
    westernZodiac: 'Balance',
    symbol: 'Lanja sy Firindrana',
    element: 'rivotra',
    elementLabelMg: 'Rivotra (Air)',
    elementLabelFr: 'Air équilibré',
    cardinalZoro: 'Andrefana-Atsimo-Andrefana',
    cardinalFr: 'Ouest-Sud-Ouest',
    solarPeriodFr: '23 Septembre – 22 Octobre',
    personalityMg:
      "Mpilatsaka an-kianja ho an'ny fihavanana, tia rariny, mahay mampitony ady ary manaja ny firindran'ny tontolo.",
    personalityFr:
      "Pacificateur, juste et esthète. Il recherche constamment l'équilibre relationnel et déteste l'injustice sous toutes ses formes.",
    strengthsMg: [
      'Fampihavanana',
      'Fandanjalanjana',
      'Hatsarana',
      'Hakingan-tsaina',
    ],
    strengthsFr: ['Médiation', "Sens de l'harmonie", 'Diplomatie', 'Élégance'],
    adviceMg: 'Sahia mandray fanapahan-kevitra hentitra rehefa ilaina izany.',
    adviceFr:
      "Tranchez quand la situation l'exige sans craindre de déplaire temporairement.",
    luckyDayMg: 'Zoma',
    luckyDayFr: 'Vendredi',
    proverbMg: "Ny marina mitovy amin'ny rano an-tovona : tsy azo afenina.",
    proverbFr: "L'équité est le ciment indéfectible de la paix commune.",
    startMonth: 9,
    startDay: 23,
    endMonth: 10,
    endDay: 22,
  },
  {
    id: 'alakarabo',
    name: 'Alakarabo',
    nameFr: 'Alakarabo (Le Clairvoyant)',
    westernZodiac: 'Scorpion',
    symbol: 'Hery Lalina sy Fandresena',
    element: 'rano',
    elementLabelMg: 'Rano (Eau)',
    elementLabelFr: 'Eau mystique',
    cardinalZoro: 'Andrefana (Ouest)',
    cardinalFr: 'Ouest (Couchant & Profondeur)',
    solarPeriodFr: '23 Octobre – 21 Novembre',
    personalityMg:
      "Manana hery anaty tsy manam-paharoa, mahay mijery ny ambadiky ny hita maso, tsy mba mora kivy na resin'ny ady.",
    personalityFr:
      'Intense, magnétique et résilient. Il perçoit ce qui échappe aux yeux et possède une remarquable capacité de régénération.',
    strengthsMg: [
      'Faharetana anaty',
      'Fahalalana lalina',
      'Fahasahiana',
      'Fahatokisana',
    ],
    strengthsFr: [
      'Résilience',
      'Intuition perçante',
      'Fidélité sans faille',
      'Courage',
    ],
    adviceMg:
      'Sokafy ny fonao ary matokia ny manodidina anao ; tsy ny rehetra no fahavalo.',
    adviceFr:
      'Accordez votre confiance plus aisément ; la vulnérabilité est aussi une force.',
    luckyDayMg: 'Talata',
    luckyDayFr: 'Mardi',
    proverbMg: 'Ny rano lalina tsy mikoriana am-bava foana.',
    proverbFr:
      "L'eau profonde s'écoule en silence ; la vraie puissance est intérieure.",
    startMonth: 10,
    startDay: 23,
    endMonth: 11,
    endDay: 21,
  },
  {
    id: 'alakaosy',
    name: 'Alakaosy',
    nameFr: 'Alakaosy (Le Destin Audacieux)',
    westernZodiac: 'Sagittaire',
    symbol: 'Tsaiky sy Tsipika Manidina',
    element: 'afo',
    elementLabelMg: 'Afo (Feu)',
    elementLabelFr: 'Feu visionnaire',
    cardinalZoro: 'Andrefana-Avaratra-Andrefana',
    cardinalFr: 'Ouest-Nord-Ouest',
    solarPeriodFr: '22 Novembre – 21 Décembre',
    personalityMg:
      'Vintana mahery vaika sy mahatalanjona. Olona manana fomba fijery lavitra, tia fahafahana ary sahy manapaka lalana vaovao.',
    personalityFr:
      'Signe à la destinée hors du commun. Aventurier, libre et idéaliste, il franchit les obstacles avec une audace lumineuse.',
    strengthsMg: [
      'Fahasahiana lehibe',
      'Fahitana lavitra',
      'Fahafahana',
      'Fanantenana',
    ],
    strengthsFr: [
      'Audace visionnaire',
      'Enthousiasme',
      "Liberté d'esprit",
      'Optimisme',
    ],
    adviceMg:
      "Omeo lanja ny fanajana ny fomban-drazana ; ny hery dia atao amin'ny fanasoavana.",
    adviceFr:
      "Canalisez votre force vers la construction et l'élévation de votre communauté.",
    luckyDayMg: 'Alakamisy',
    luckyDayFr: 'Jeudi',
    proverbMg: 'Ny vorona mahay manidina tsy mba matahotra ny havoana.',
    proverbFr:
      "L'oiseau qui sait déployer ses ailes ne craint jamais les sommets.",
    startMonth: 11,
    startDay: 22,
    endMonth: 12,
    endDay: 21,
  },
  {
    id: 'adijady',
    name: 'Adijady',
    nameFr: 'Adijady (Le Sage Bâtisseur)',
    westernZodiac: 'Capricorne',
    symbol: 'Vato Vatolampy sy Tendrombohitra',
    element: 'tany',
    elementLabelMg: 'Tany (Terre)',
    elementLabelFr: 'Terre immuable',
    cardinalZoro: 'Zoro Adijady (Avaratra-Andrefana)',
    cardinalFr: 'Nord-Ouest (Pilier de la tradition)',
    solarPeriodFr: '22 Décembre – 19 Janvier',
    personalityMg:
      "Olona vato fehizoro, matotra mialoha ny taonany, manaja ny teny nomena ary manangana zava-maharitra ho an'ny taranaka.",
    personalityFr:
      'Pilier de sagesse et de rigueur. Dévoué à la transmission, il bâtit des réussites solides et durables défiant le temps.',
    strengthsMg: [
      'Fahatokisana',
      'Fahamasinana',
      'Fahazotoana',
      "Fahendren'ny ntaolo",
    ],
    strengthsFr: [
      'Constance',
      'Sens du devoir',
      'Patience',
      "Profondeur d'esprit",
    ],
    adviceMg:
      'Manokana fotoana hialana voly sy hifaliana ; mendrika fitsaharana ny ezaka.',
    adviceFr:
      'Accordez-vous de la légèreté ; le repos est le complice des grandes victoires.',
    luckyDayMg: 'Sabotsy',
    luckyDayFr: 'Samedi',
    proverbMg:
      'Ny vato mitambatra mahatonga trano, ny teny iombonana mahatonga firaisana.',
    proverbFr:
      'Les pierres unies forment la demeure, la parole tenue forge la confiance.',
    startMonth: 12,
    startDay: 22,
    endMonth: 1,
    endDay: 19,
  },
  {
    id: 'adalo',
    name: 'Adalo',
    nameFr: 'Adalo (Le Rénovateur Solidaire)',
    westernZodiac: 'Verseau',
    symbol: 'Loharano Mandriaka',
    element: 'rivotra',
    elementLabelMg: 'Rivotra (Air)',
    elementLabelFr: "Air d'avant-garde",
    cardinalZoro: 'Avaratra (Nord)',
    cardinalFr: 'Nord (Source de renouveau)',
    solarPeriodFr: '20 Janvier – 18 Février',
    personalityMg:
      "Mpandrava ny mahazatra ho an'ny fandrosoana, manana eritreritra ambony, tia mifanome tanana ary tsy tia fitongilanana.",
    personalityFr:
      'Inventif, humaniste et avant-gardiste. Il place la fraternité au sommet de ses idéaux et trouve des voies inédites pour avancer.',
    strengthsMg: [
      'Famoronana',
      'Firaisankina',
      'Fahalalahana',
      'Hatsaram-panahy',
    ],
    strengthsFr: ['Créativité', 'Fraternité', 'Originalité', 'Bienveillance'],
    adviceMg:
      'Mijanona ho akaiky ny zava-misy mivaingana rehefa mamolavola vina lehibe.',
    adviceFr:
      'Ancrez vos grandes idées dans des actions concrètes au quotidien.',
    luckyDayMg: 'Asabotsy',
    luckyDayFr: 'Samedi',
    proverbMg: 'Ny hevi-baovao manasoa ny maro no harena lehibe indrindra.',
    proverbFr:
      'Les idées éclairées partagées avec tous sont la plus noble des richesses.',
    startMonth: 1,
    startDay: 20,
    endMonth: 2,
    endDay: 18,
  },
  {
    id: 'alohotsy',
    name: 'Alohotsy',
    nameFr: "Alohotsy (L'Âme Poétique)",
    westernZodiac: 'Poissons',
    symbol: 'Ranomasina sy Nofy Masina',
    element: 'rano',
    elementLabelMg: 'Rano (Eau)',
    elementLabelFr: 'Eau spirituelle',
    cardinalZoro: 'Avaratra-Avaratra-Atsinanana',
    cardinalFr: 'Nord-Nord-Est',
    solarPeriodFr: '19 Février – 20 Mars',
    personalityMg:
      "Tia zavakanto, be fiantrana, manana saina misidina any amin'ny hatsarana ary mahatsapa ny fihetseham-pon'ny hafa rehetra.",
    personalityFr:
      "Poète dans l'âme, sensible et compatissant. Doté d'une profonde dimension spirituelle, il répand la paix et la douceur.",
    strengthsMg: [
      'Fahaiza-mamorona',
      'Fiaraha-miory',
      'Hatsarana ara-panahy',
      'Fiadanana',
    ],
    strengthsFr: [
      'Sens artistique',
      'Compassion',
      'Intuition',
      "Douceur d'âme",
    ],
    adviceMg:
      "Arovy ny fonao tsy ho azon'ny fitaka ; mitandrema amin'ny hatsaram-panahy tafahoatra.",
    adviceFr:
      'Fixez des limites bienveillantes pour préserver votre précieux équilibre émotionnel.',
    luckyDayMg: 'Alakamisy',
    luckyDayFr: 'Jeudi',
    proverbMg: "Ny feon'ny fo madio no mahare ny bitsiky ny lanitra.",
    proverbFr:
      "Le cœur pur entend le murmure de l'infini et apporte l'apaisement.",
    startMonth: 2,
    startDay: 19,
    endMonth: 3,
    endDay: 20,
  },
];
